name: Rust
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€

on:
  push:
    branches: [ "gh-actions" ]
  pull_request:
    branches: [ "gh-actions" ]


env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - name: Check out repository code
      uses: actions/checkout@v4
    - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
    - name: Install dfx and dependencies 
      run: |
        sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
        npm install 
        mkdir src/civic_canister_backend/dist
    - name: Install canisters and start local ICP replica
      run: |
        dfx start --clean --background
        dfx canister create --all
    - name: Build canisters
      run: dfx build --verbose
    - name: Deploy canisters
      run: dfx canister install --all && dfx deploy 
    - name: Run tests
      run: cargo test --test integration_tests --verbose
    - run: echo "ğŸ This job's status is ${{ job.status }}."
